files:
  include:
    - 'scss/**/*.scss'
    - 'test/**/*.scss'
syntax:
    include:
      - scss
      - sass
options:
  formatter: stylish
  merge-default-rules: true
rules:
  property-sort-order:
    - 1
    - order: smacss
  placeholder-in-extend: 0
  no-important: 0
  no-vendor-prefixes: 0
